db:
    image: drupal/mysql
    ports:
        - 3306:3306
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
        - ./db:/var/lib/mysql
    expose:
        - "3306"

drupal:
    image: drupal/code
    volumes:
        - ./themes_contrib:/var/www/html/sites/all/themes/contrib
        - ./themes_custom:/var/www/html/sites/all/themes/custom
        - ./modules_contrib:/var/www/html/sites/all/modules/contrib
        - ./modules_custom:/var/www/html/sites/all/modules/custom
        - ./files:/var/www/html/sites/default/files
    links:
        - db
    tty: true
